# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/gvillage_dev
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: root
  password: root
  

test:
  <<: *default
  database: db/gvillage_tst

production:
  <<: *default
  database: db/production.sqlite3
