# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2301bcfd245b774b7fb65f8e11a5026a42d5c646d423d928cfe744ef7a7bfe179a97d45874383794c307490665d7d732d953d665f2f27d94391a9363e3fc4ad9

test:
  secret_key_base: ee17da6b11dc2ab894f7147b8cad2f420760b7d40419970d9a7f2bdd73eabeb58758fe3fbbc857be9133e7d3df6814743a00b2db4c18a48afd686b0b1d760336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
